SELECT
 LAKE_NAME
, YEAR(START_DATE) AS Year
, CASE
  -- Calculates lake health, with 1 being the best, and 0 being the worst
  -- Assumes total phosphorous .55 is the optimal level for health
  -- Due to total phosphorous ppm < .01 causing a lack of nutrients, and > 0.1 being eutrophic
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.0525 AND 0.0575 THEN 1
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.05 AND 0.06 THEN 0.9
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.045 AND 0.065 THEN 0.8
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.04 AND 0.07 THEN 0.7
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.035 AND 0.075 THEN 0.6
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.03 AND 0.08 THEN 0.5
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.025 AND 0.085 THEN 0.4
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.02 AND 0.09 THEN 0.3
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.015 AND 0.095 THEN 0.2
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) BETWEEN 0.01 AND 0.1 THEN 0.1
    WHEN AVG(TOTAL_PHOSPHORUS_RESULT) IS NULL THEN NULL 
   ELSE 0 END AS LakeHealth
, AVG(TOTAL_PHOSPHORUS_RESULT) AS AvgPhosphorous
, AVG(SECCHI_DEPTH_RESULT) AS AvgSecchiDepth
FROM [datadive-142319:mces_lakes.1999_2014_monitoring_data] 
WHERE SEASONAL_LAKE_GRADE_RESULT IS NULL
  AND YEAR(START_DATE) >= 2004
GROUP BY LAKE_NAME, Year
